### ISSUE TITLE
Package not found

### ISSUE THREAD

**Issue by Gjeorgjia** [oscgonfer/sensors_dsp_lectures#1]
Step 2.b.4 after trying to install the yml file, this issue appears:

ResolvePackageNotFound: 
- markupsafe==1.1.1=py37h1de35cc_0
- yaml==0.2.2=h0b31af3_1
- pyrsistent==0.15.6=py37h1de35cc_0
- zeromq==4.3.1=h0a44026_3
- xz==5.2.4=h1de35cc_4
- tk==8.6.8=ha441bb4_0
- zlib==1.2.11=h1de35cc_3
- libsodium==1.0.16=h3efe00b_0
- sqlite==3.30.1=ha441bb4_0
- openssl==1.1.1d=h0b31af3_0
- readline==7.0=h1de35cc_5
- python==3.7.5=h359304d_0
- libedit==3.1.20181209=hb402a30_0
- libffi==3.2.1=h475c297_4
- libcxx==4.0.1=hcfea43d_1
- ncurses==6.1=h0a44026_1
- libcxxabi==4.0.1=hcfea43d_1
- tornado==6.0.3=py37h1de35cc_0
- mistune==0.8.4=py37h1de35cc_0

**Comment by oscgonfer** [comment]
Hi, 

Try pulling or using the new [environment.yml](https://github.com/oscgonfer/sensors_dsp_lectures/blob/master/environment.yml).

**Comment by oscgonfer** [comment]
#c99784e59bd26da82207832582d4a4461197c617
